### ISSUE TITLE
Hawk Auth should use queryparams

### ISSUE THREAD

**Issue by DaniCastroDev** [tiagohm/restio#11]
Hi!
I have been trying to use this package because of the hawk auth, but I have been having some troubles using it.
I am not an expert using hawk auth, but there were some times where the authentication does not work.
Upon further investigation (generating the auth token with postman), i have found that the query params should be included in the resource part of the encoding, but they are not included, therefore the mac is not being generated properly.

**Comment by tiagohm** [comment]
> i have found that the query params should be included in the resource part of the encoding, but they are not included, therefore the mac is not being generated properly

You are right. I did a test hitting the endpoint `https://postman-echo.com/auth/hawk?a=b` and received an error 401.

Thanks for filing this issue. I will fix it.
