### ISSUE TITLE
how can i add the header in the get request???

### ISSUE THREAD

**Issue by zjiale** [tiagohm/restio#4]
I didn't find relevant instructions in the documentation

**Comment by tiagohm** [comment]
```dart
final request = Request.get(
      'https://httpbin.org/get',
      headers: (HeadersBuilder()..add('name', 'value')).build(),
    );
```

or

```dart
final request = Request.get(
      'https://httpbin.org/get',
      headers: Headers.fromMap({'name': 'value'}),
    );
```

**Comment by zjiale** [comment]
> ```dart
> final request = Request.get(
>       'https://httpbin.org/get',
>       headers: (HeadersBuilder()..add('name', 'value')).build(),
>     );
> ```
> 
> or
> 
> ```dart
> final request = Request.get(
>       'https://httpbin.org/get',
>       headers: Headers.of({'name': 'value'}),
>     );
> ```

Thanks bro！！！
